export const userData=[
  {
    id: 3841,
    name: "Usha Chattopadhyay",
    email: "chattopadhyay_usha@rohan-dicki.name",
    gender: "female",
    status: "active",
  },
  {
    id: 3840,
    name: "Diksha Somayaji",
    email: "diksha_somayaji@homenick-hettinger.com",
    gender: "male",
    status: "inactive",
  },
  {
    id: 3838,
    name: "Indra Mukhopadhyay",
    email: "indra_mukhopadhyay@conn-bergstrom.name",
    gender: "male",
    status: "inactive",
  },
  {
    id: 3837,
    name: "Dhananjay Patel",
    email: "patel_dhananjay@kris-dibbert.org",
    gender: "female",
    status: "active",
  },
  {
    id: 3835,
    name: "Malti Ganaka",
    email: "ganaka_malti@volkman.co",
    gender: "male",
    status: "inactive",
  },
  {
    id: 3832,
    name: "Bhaaswar Kocchar",
    email: "bhaaswar_kocchar@mohr-flatley.io",
    gender: "female",
    status: "active",
  },
  {
    id: 3831,
    name: "Shanti Panicker",
    email: "panicker_shanti@buckridge.co",
    gender: "male",
    status: "inactive",
  },
  {
    id: 3830,
    name: "Vasundhara Dhawan",
    email: "dhawan_vasundhara@okuneva.info",
    gender: "male",
    status: "active",
  },
  {
    id: 3829,
    name: "Gandharv Achari",
    email: "achari_gandharv@abshire-bednar.net",
    gender: "male",
    status: "inactive",
  },
  {
    id: 3828,
    name: "Buddhana Sharma",
    email: "sharma_buddhana@wisoky-yundt.biz",
    gender: "female",
    status: "inactive",
  },
  {
    id: 3827,
    name: "Deependra Dubashi",
    email: "dubashi_deependra@ziemann.info",
    gender: "female",
    status: "active",
  },
  {
    id: 3826,
    name: "Suryakantam Jha",
    email: "jha_suryakantam@damore.com",
    gender: "male",
    status: "active",
  },
  {
    id: 3825,
    name: "Manjusha Bhattacharya",
    email: "bhattacharya_manjusha@bode-borer.name",
    gender: "female",
    status: "active",
  },
  {
    id: 3824,
    name: "Dinkar Kapoor",
    email: "kapoor_dinkar@nikolaus.org",
    gender: "female",
    status: "inactive",
  },
  {
    id: 3823,
    name: "Swarnalata Mahajan",
    email: "swarnalata_mahajan@king-oberbrunner.org",
    gender: "female",
    status: "inactive",
  },
  {
    id: 3822,
    name: "Kanaka Prajapat",
    email: "kanaka_prajapat@huels-strosin.com",
    gender: "male",
    status: "active",
  },
  {
    id: 3821,
    name: "Mr. Suryakanta Gowda",
    email: "suryakanta_mr_gowda@heaney.io",
    gender: "female",
    status: "active",
  },
  {
    id: 3820,
    name: "Devajyoti Agarwal",
    email: "agarwal_devajyoti@miller.com",
    gender: "male",
    status: "inactive",
  },
  {
    id: 3819,
    name: "Gov. Leela Dwivedi",
    email: "dwivedi_gov_leela@collins-adams.com",
    gender: "male",
    status: "active",
  },
  {
    id: 3818,
    name: "Anandamayi Butt",
    email: "anandamayi_butt@thiel-mueller.io",
    gender: "male",
    status: "active",
  },
];

export const userRows = [
    { id: 1, lastName: 'Snow', firstName: 'Jon', age: 35 },
    { id: 2, lastName: 'Lannister', firstName: 'Cersei', age: 42 },
    { id: 3, lastName: 'Lannister', firstName: 'Jaime', age: 45 },
    { id: 4, lastName: 'Stark', firstName: 'Arya', age: 16 },
    { id: 5, lastName: 'Targaryen', firstName: 'Daenerys', age: null },
    { id: 6, lastName: 'Melisandre', firstName: "alure", age: 150 },
    { id: 7, lastName: 'Clifford', firstName: 'Ferrara', age: 44 },
    { id: 8, lastName: 'Frances', firstName: 'Rossini', age: 36 },
    { id: 9, lastName: 'Roxie', firstName: 'Harvey', age: 65 },
  ];